# Generated by Django 3.1.4 on 2020-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('theme', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Stickers',
            },
        ),
        migrations.AlterModelOptions(
            name='bags',
            options={'verbose_name_plural': 'Bags'},
        ),
        migrations.AlterModelOptions(
            name='scoops',
            options={'verbose_name_plural': 'Scoops'},
        ),
    ]
