# Generated by Django 3.1.4 on 2020-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_card_picture'),
        ('sweets', '0002_auto_20201211_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bags',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='scoops',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='stickers',
            name='picture',
        ),
        migrations.AddField(
            model_name='bags',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bags',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='scoops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scoops',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='stickers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stickers',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
