# Generated by Django 3.1.4 on 2020-12-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_scoops_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='scoops',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sweets.scoops'),
        ),
    ]
