# Generated by Django 3.1.4 on 2020-12-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_bags_scoops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bags',
            name='scoops',
        ),
        migrations.AddField(
            model_name='bags',
            name='scoops',
            field=models.ManyToManyField(blank=True, to='sweets.Scoops'),
        ),
    ]
