# Generated by Django 3.1.4 on 2020-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0006_auto_20201223_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='scoops',
            field=models.ManyToManyField(blank=True, related_name='scoop', to='sweets.Scoops'),
        ),
    ]
