# Generated by Django 3.1.4 on 2020-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0007_auto_20201223_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='duplicate_scoops',
            field=models.BooleanField(null=True),
        ),
    ]
