# Generated by Django 3.1.4 on 2020-12-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0008_bags_duplicate_scoops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='is_vegetarian',
            field=models.BooleanField(null=True),
        ),
    ]
