# Generated by Django 3.1.4 on 2020-12-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0009_auto_20201230_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='duplicate_scoop_ids',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bags',
            name='duplicate_scoops',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bags',
            name='is_vegetarian',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
