# Generated by Django 3.1.4 on 2020-12-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sweets', '0002_auto_20201211_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sweets.pictures')),
            ],
        ),
    ]
