# Generated by Django 3.1.4 on 2020-12-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
